"""
Django settings for lupus_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import secrets
from corsheaders.defaults import default_headers

# Load environment variables from .env file
load_dotenv()

# ------------------------------------------------------------
# Determine Environment (dev or prod)
# ------------------------------------------------------------
ENVIRONMENT = os.getenv('DJANGO_ENV', 'dev').lower() 
IS_PROD = ENVIRONMENT == "prod"
IS_DEV = ENVIRONMENT == "dev"

# ------------------------------------------------------------
# BASE DIR
# ------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------
# SECRET KEY
# ------------------------------------------------------------
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    SECRET_KEY = secrets.token_urlsafe(50)
    
# ------------------------------------------------------------
# DEBUG
# ------------------------------------------------------------
DEBUG = False if IS_PROD else True

# ------------------------------------------------------------
# Hosts & CORS
# ------------------------------------------------------------
ALLOWED_HOSTS = [h for h in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if h] if IS_PROD else ['localhost', '127.0.0.1']
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(',') if IS_PROD else [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000"
]
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if IS_PROD else ["http://localhost:5173", "http://127.0.0.1:5173", "http://localhost:3000"]

# ------------------------------------------------------------
# Cookies
# ------------------------------------------------------------
SESSION_COOKIE_SECURE = True if IS_PROD else False
CSRF_COOKIE_SECURE = True if IS_PROD else False
SESSION_COOKIE_HTTPONLY = True if IS_PROD else False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# ------------------------------------------------------------
# HTTPS & HSTS
# ------------------------------------------------------------
SECURE_SSL_REDIRECT = True if IS_PROD else False
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000')) if IS_PROD else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True if IS_PROD else False
SECURE_HSTS_PRELOAD = True if IS_PROD else False
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if IS_PROD else None

# ------------------------------------------------------------
# Security Headers
# ------------------------------------------------------------
SECURE_CONTENT_TYPE_NOSNIFF = True if IS_PROD else False
X_FRAME_OPTIONS = 'DENY' if IS_PROD else 'SAMEORIGIN'
SECURE_REFERRER_POLICY = 'same-origin' if IS_PROD else None

# ------------------------------------------------------------
# Installed Apps & Middleware
# ------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise middleware (only used in prod)
    'whitenoise.middleware.WhiteNoiseMiddleware' if IS_PROD else None,
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Filter out None values in MIDDLEWARE (so it doesn't break dev)
MIDDLEWARE = [mw for mw in MIDDLEWARE if mw]

CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-frontend-key',
]

# Frontend Token
FE_TOKEN = os.getenv('FE_TOKEN', 'dev-secret_23451@@@!!!!') 


# ------------------------------------------------------------ 
# URL Configuration & Templates
# ------------------------------------------------------------
ROOT_URLCONF = 'lupus_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lupus_backend.wsgi.application'


# ------------------------------------------------------------ 
# Database
# ------------------------------------------------------------
if IS_PROD:
    print("Production database settings...")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_PROD_NAME'),
            'USER': os.getenv('DB_PROD_USER'),
            'PASSWORD': os.getenv('DB_PROD_PASSWORD'),
            'HOST': os.getenv('DB_PROD_HOST'),
            'PORT': os.getenv('DB_PROD_PORT', '5432'),
            'OPTIONS': {
                'sslmode': os.getenv('DB_PROD_SSL_MODE', 'require')
            }
        }
    }
else:
    print("Development database settings...")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_DEV_NAME'),
            'USER': os.getenv('DB_DEV_USER'),
            'PASSWORD': os.getenv('DB_DEV_PASSWORD'),
            'HOST': 'db',  # Docker service name for your local Postgres container
            'PORT': '5432'
        }
    }


# ------------------------------------------------------------ 
# Default primary key field type 
# ------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ------------------------------------------------------------ 
# Password Validation 
# ------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ------------------------------------------------------------ 
# Internationalization 
# ------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------ 
# Static files 
# ------------------------------------------------------------

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise storage backend for production
if IS_PROD:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ------------------------------------------------------------ 
# Default primary key field type 
# ------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
